[plotly-artifacts]
git-tree-sha1 = "5c22a3e015789a93a433debcf905adf8a2d51ad9"

    [[plotly-artifacts.download]]
    sha256 = "a9b8595f1eb014d0a77ae6af9bf5e268a79f2891a0b13578c9acff31d544dc81"
    url = "https://github.com/halleysfifthinc/PlotlyJS.jl/releases/download/plotly-artifacts-2.31.1/plotly-artifacts-2.31.1.tar.gz"
